config/routes.rb
Iot::Application.routes.draw do
  get "recipe/find"
  resources :items

  resources :shopping_lists

  resources :past_recipes

  resources :fridges

  resources :categories

  resources :users

  

end

app/models/fridge.rb
class Fridge < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
  before_action :set_fridge, only: [:show, :edit, :update, :destroy]

  # GET /fridges
  # GET /fridges.json
  def index
    @fridges = Fridge.all
  end

  # GET /fridges/1
  # GET /fridges/1.json
  def show
  end

  # GET /fridges/new
  def new
    @fridge = Fridge.new
  end

  # GET /fridges/1/edit
  def edit
  end

  # POST /fridges
  # POST /fridges.json
  def create
    @fridge = Fridge.new(fridge_params)

    respond_to do |format|
      if @fridge.save
        format.html { redirect_to @fridge, notice: 'Fridge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fridge }
      else
        format.html { render action: 'new' }
        format.json { render json: @fridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fridges/1
  # PATCH/PUT /fridges/1.json
  def update
    respond_to do |format|
      if @fridge.update(fridge_params)
        format.html { redirect_to @fridge, notice: 'Fridge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fridges/1
  # DELETE /fridges/1.json
  def destroy
    @fridge.destroy
    respond_to do |format|
      format.html { redirect_to fridges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fridge
      @fridge = Fridge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fridge_params
      params.require(:fridge).permit(:item_id, :quantity, :user_id, :date_bought)
    end
end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/views/fridges/_form.html.erb
<%= form_for(@fridge) do |f| %>
  <% if @fridge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fridge.errors.count, "error") %> prohibited this fridge from being saved:</h2>

      <ul>
      <% @fridge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.select :item_id,
                 Item.all.map { |p| [p.name, p.id] },
                 {include_blank: 'Choose...'},
                 selected: @item.try(:item).try(:id) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id,
                 User.all.map { |p| [p.name, p.id] },
                 {include_blank: 'Choose...'},
                 selected: @user.try(:user).try(:id) %>
  </div>
  <div class="field">
    <%= f.label :date_bought %><br>
    <%= f.date_select :date_bought %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fridges/edit.html.erb
<h1>Editing fridge</h1>

<%= render 'form' %>

<%= link_to 'Show', @fridge %> |
<%= link_to 'Back', fridges_path %>

app/views/fridges/index.html.erb
<h1>Listing fridges</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>User</th>
      <th>Date bought</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fridges.each do |fridge| %>
      <tr>
        <td><%= fridge.item_id %></td>
        <td><%= fridge.quantity %></td>
        <td><%= fridge.user_id %></td>
        <td><%= fridge.date_bought %></td>
        <td><%= link_to 'Show', fridge %></td>
        <td><%= link_to 'Edit', edit_fridge_path(fridge) %></td>
        <td><%= link_to 'Destroy', fridge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fridge', new_fridge_path %>

app/views/fridges/new.html.erb
<h1>New fridge</h1>

<%= render 'form' %>

<%= link_to 'Back', fridges_path %>

app/views/fridges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @fridge.item_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @fridge.quantity %>
</p>

<p>
  <strong>User:</strong>
  <%= @fridge.user_id %>
</p>

<p>
  <strong>Date bought:</strong>
  <%= @fridge.date_bought %>
</p>

<%= link_to 'Edit', edit_fridge_path(@fridge) %> |
<%= link_to 'Back', fridges_path %>