config/routes.rb
Iot::Application.routes.draw do
  get "recipe/find"
  resources :items

  resources :shopping_lists

  resources :past_recipes

  resources :fridges

  resources :categories

  resources :users

  

end

app/models/past_recipe.rb
class PastRecipe < ActiveRecord::Base
  belongs_to :user
end

app/controllers/past_recipes_controller.rb
class PastRecipesController < ApplicationController
  before_action :set_past_recipe, only: [:show, :edit, :update, :destroy]

  # GET /past_recipes
  # GET /past_recipes.json
  def index
    @past_recipes = PastRecipe.all
  end

  # GET /past_recipes/1
  # GET /past_recipes/1.json
  def show
  end

  # GET /past_recipes/new
  def new
    @past_recipe = PastRecipe.new
  end

  # GET /past_recipes/1/edit
  def edit
  end

  # POST /past_recipes
  # POST /past_recipes.json
  def create
    @past_recipe = PastRecipe.new(past_recipe_params)

    respond_to do |format|
      if @past_recipe.save
        format.html { redirect_to @past_recipe, notice: 'Past recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @past_recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @past_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /past_recipes/1
  # PATCH/PUT /past_recipes/1.json
  def update
    respond_to do |format|
      if @past_recipe.update(past_recipe_params)
        format.html { redirect_to @past_recipe, notice: 'Past recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @past_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /past_recipes/1
  # DELETE /past_recipes/1.json
  def destroy
    @past_recipe.destroy
    respond_to do |format|
      format.html { redirect_to past_recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_past_recipe
      @past_recipe = PastRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def past_recipe_params
      params.require(:past_recipe).permit(:user_id, :pearson_identity, :date_made)
    end
end

app/helpers/past_recipes_helper.rb
module PastRecipesHelper
end

app/views/past_recipes/_form.html.erb
<%= form_for(@past_recipe) do |f| %>
  <% if @past_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@past_recipe.errors.count, "error") %> prohibited this past_recipe from being saved:</h2>

      <ul>
      <% @past_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id,
                 User.all.map { |p| [p.name, p.id] },
                 {include_blank: 'Choose...'},
                 selected: @user.try(:user).try(:id) %>
  </div>
  <div class="field">
    <%= f.label :pearson_identity %><br>
    <%= f.text_field :pearson_identity %>
  </div>
  <div class="field">
    <%= f.label :date_made %><br>
    <%= f.date_select :date_made %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/past_recipes/edit.html.erb
<h1>Editing past_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @past_recipe %> |
<%= link_to 'Back', past_recipes_path %>

app/views/past_recipes/index.html.erb
<h1>Listing past_recipes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pearson identity</th>
      <th>Date made</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @past_recipes.each do |past_recipe| %>
      <tr>
        <td><%= past_recipe.user_id %></td>
        <td><%= past_recipe.pearson_identity %></td>
        <td><%= past_recipe.date_made %></td>
        <td><%= link_to 'Show', past_recipe %></td>
        <td><%= link_to 'Edit', edit_past_recipe_path(past_recipe) %></td>
        <td><%= link_to 'Destroy', past_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Past recipe', new_past_recipe_path %>

app/views/past_recipes/new.html.erb
<h1>New past_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', past_recipes_path %>

app/views/past_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @past_recipe.user_id %>
</p>

<p>
  <strong>Pearson identity:</strong>
  <%= @past_recipe.pearson_identity %>
</p>

<p>
  <strong>Date made:</strong>
  <%= @past_recipe.date_made %>
</p>

<%= link_to 'Edit', edit_past_recipe_path(@past_recipe) %> |
<%= link_to 'Back', past_recipes_path %>